"""schema v0: source, fetch_run, source_document

Revision ID: 0001
Revises:
Create Date: 2026-09-18 07:54:41.149689
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before the embedding column is created. The
    # docker-compose image and Neon both ship it; this makes a bare
    # PostgreSQL 16 work too.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("tier", sa.Text(), nullable=False),
        sa.Column(
            "params", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("schedule", sa.Text(), server_default="daily", nullable=False),
        sa.Column("licence_note", sa.Text(), nullable=True),
        sa.Column("domains", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('arxiv_category', 'biorxiv', 'rss', 'openalex', 'ror')",
            name=op.f("ck_source_kind_valid"),
        ),
        sa.CheckConstraint("tier IN ('T1', 'T2', 'T3', 'T4')", name=op.f("ck_source_tier_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
    )
    op.create_table(
        "fetch_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("fetched_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("new_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'ok', 'error')", name=op.f("ck_fetch_run_status_valid")
        ),
        sa.CheckConstraint(
            "fetched_count >= 0 AND new_count >= 0", name=op.f("ck_fetch_run_counts_non_negative")
        ),
        sa.CheckConstraint(
            "new_count <= fetched_count", name=op.f("ck_fetch_run_new_not_above_fetched")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_fetch_run_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fetch_run")),
    )
    op.create_index(op.f("ix_fetch_run_source_id"), "fetch_run", ["source_id"], unique=False)
    op.create_table(
        "source_document",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column(
            "external_id",
            sa.Text(),
            nullable=False,
            comment="Feed-supplied identifier, or the URL when none is given.",
        ),
        sa.Column(
            "canonical_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Stable identifiers: {doi, arxiv, openalex, pmid}.",
        ),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("authors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column(
            "content_text",
            sa.Text(),
            nullable=True,
            comment="Transient extraction input. Cleared after extraction where the source licence does not permit storage (docs/02 section E.6).",
        ),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("licence", sa.Text(), nullable=True),
        sa.Column("tier_override", sa.Text(), nullable=True),
        sa.Column("lifecycle", sa.Text(), server_default="fetched", nullable=False),
        sa.Column("duplicate_of", sa.UUID(), nullable=True),
        sa.Column("fetch_run_id", sa.UUID(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(title, '') || ' ' || coalesce(abstract, ''))",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lifecycle <> 'duplicate' OR duplicate_of IS NOT NULL",
            name=op.f("ck_source_document_duplicate_has_target"),
        ),
        sa.CheckConstraint(
            "lifecycle IN ('fetched', 'duplicate', 'irrelevant', 'triaged', 'extracted', 'linked', 'assessed')",
            name=op.f("ck_source_document_lifecycle_valid"),
        ),
        sa.CheckConstraint(
            "tier_override IS NULL OR tier_override IN ('T1', 'T2', 'T3', 'T4')",
            name=op.f("ck_source_document_tier_override_valid"),
        ),
        sa.CheckConstraint(
            "duplicate_of IS NULL OR duplicate_of <> id",
            name=op.f("ck_source_document_duplicate_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of"],
            ["source_document.id"],
            name=op.f("fk_source_document_duplicate_of_source_document"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["fetch_run_id"],
            ["fetch_run.id"],
            name=op.f("fk_source_document_fetch_run_id_fetch_run"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_source_document_source_id_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_document")),
        sa.UniqueConstraint(
            "source_id", "external_id", name="uq_source_document_source_id_external_id"
        ),
    )
    op.create_index(
        "ix_source_document_content_hash", "source_document", ["content_hash"], unique=False
    )
    op.create_index(
        "ix_source_document_embedding",
        "source_document",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index("ix_source_document_lifecycle", "source_document", ["lifecycle"], unique=False)
    op.create_index(
        "ix_source_document_published_at", "source_document", ["published_at"], unique=False
    )
    op.create_index(
        "ix_source_document_search_tsv",
        "source_document",
        ["search_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_source_document_source_id"), "source_document", ["source_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # The vector extension is deliberately left installed: dropping it would
    # affect anything else in the database that uses it.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_document_source_id"), table_name="source_document")
    op.drop_index(
        "ix_source_document_search_tsv", table_name="source_document", postgresql_using="gin"
    )
    op.drop_index("ix_source_document_published_at", table_name="source_document")
    op.drop_index("ix_source_document_lifecycle", table_name="source_document")
    op.drop_index(
        "ix_source_document_embedding",
        table_name="source_document",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index("ix_source_document_content_hash", table_name="source_document")
    op.drop_table("source_document")
    op.drop_index(op.f("ix_fetch_run_source_id"), table_name="fetch_run")
    op.drop_table("fetch_run")
    op.drop_table("source")
    # ### end Alembic commands ###
