"""schema v1: technologies, developments, claims, analysis runs and review

Revision ID: a07180465579
Revises: 0001
Create Date: 2026-09-18 19:37:34.573298
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column(
            "prompt_version",
            sa.Text(),
            nullable=False,
            comment="Git SHA of the prompt file used for this call.",
        ),
        sa.Column("input_ids", postgresql.ARRAY(sa.UUID()), server_default="{}", nullable=False),
        sa.Column(
            "raw_output",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="The model's response before validation, kept for debugging.",
        ),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("records_written", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "ungrounded_claims",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Claims discarded because the quote was not found in the source.",
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "stage IN ('triage', 'extract', 'dedupe', 'assess', 'relate', 'summarise')",
            name=op.f("ck_analysis_run_stage_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('ok', 'schema_error', 'refusal', 'error')",
            name=op.f("ck_analysis_run_status_valid"),
        ),
        sa.CheckConstraint(
            "cost_usd IS NULL OR cost_usd >= 0", name=op.f("ck_analysis_run_cost_not_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_run")),
    )
    op.create_index(
        "ix_analysis_run_stage_created_at", "analysis_run", ["stage", "created_at"], unique=False
    )
    op.create_table(
        "domain",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domain")),
    )
    op.create_table(
        "organization",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ror_id", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True, comment="ISO 3166-1 alpha-2."),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("aliases", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("status", sa.Text(), server_default="proposed", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IS NULL OR kind IN ('university', 'company', 'government', 'lab', 'nonprofit', 'consortium')",
            name=op.f("ck_organization_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'active', 'merged', 'retired')",
            name=op.f("ck_organization_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization")),
        sa.UniqueConstraint("ror_id", name=op.f("uq_organization_ror_id")),
    )
    op.create_index("ix_organization_name", "organization", ["name"], unique=False)
    op.create_table(
        "review_task",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IN ('new_entity', 'high_stage', 'conflict', 'low_confidence', 'ungrounded_quote', 'user_report')",
            name=op.f("ck_review_task_reason_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'done', 'dismissed')", name=op.f("ck_review_task_status_valid")
        ),
        sa.CheckConstraint(
            "target_type IN ('claim', 'technology', 'organization', 'development', 'assessment', 'relation', 'correction')",
            name=op.f("ck_review_task_target_type_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_task")),
    )
    op.create_index(
        "ix_review_task_status_priority", "review_task", ["status", "priority"], unique=False
    )
    op.create_index(
        "ix_review_task_target_type_target_id",
        "review_task",
        ["target_type", "target_id"],
        unique=False,
    )
    op.create_table(
        "development",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=True),
        sa.Column("occurred_basis", sa.Text(), nullable=True),
        sa.Column(
            "summary",
            sa.Text(),
            nullable=True,
            comment="Generated interpretation. Labelled as such wherever it is shown.",
        ),
        sa.Column("summary_run_id", sa.UUID(), nullable=True),
        sa.Column("summary_stale", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status", sa.Text(), server_default="proposed", nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', title || ' ' || coalesce(summary, ''))", persisted=True
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('paper', 'demonstration', 'pilot', 'product', 'regulatory', 'funding', 'other')",
            name=op.f("ck_development_kind_valid"),
        ),
        sa.CheckConstraint(
            "occurred_on IS NULL OR (occurred_basis IS NOT NULL AND occurred_basis IN ('document_metadata', 'quoted_text'))",
            name=op.f("ck_development_occurred_has_basis"),
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'active', 'merged', 'retired')",
            name=op.f("ck_development_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["summary_run_id"],
            ["analysis_run.id"],
            name=op.f("fk_development_summary_run_id_analysis_run"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_development")),
        sa.UniqueConstraint("slug", name=op.f("uq_development_slug")),
    )
    op.create_index(
        "ix_development_embedding",
        "development",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index("ix_development_occurred_on", "development", ["occurred_on"], unique=False)
    op.create_index(
        "ix_development_search_tsv",
        "development",
        ["search_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "review_action",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("actor_id", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('accept', 'edit', 'reject', 'merge', 'retract')",
            name=op.f("ck_review_action_action_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["review_task.id"],
            name=op.f("fk_review_action_task_id_review_task"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_action")),
    )
    op.create_table(
        "technology",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("domain_id", sa.Text(), nullable=False),
        sa.Column(
            "scope_note",
            sa.Text(),
            nullable=False,
            comment="What is and is not included. Required; see the class docstring.",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Curator-written."),
        sa.Column("openalex_query", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("featured", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status", sa.Text(), server_default="proposed", nullable=False),
        sa.Column("merged_into", sa.UUID(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', name || ' ' || coalesce(description, ''))", persisted=True
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'merged' OR merged_into IS NOT NULL",
            name=op.f("ck_technology_merged_has_target"),
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'active', 'merged', 'retired')",
            name=op.f("ck_technology_status_valid"),
        ),
        sa.CheckConstraint(
            "merged_into IS NULL OR merged_into <> id", name=op.f("ck_technology_merged_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domain.id"],
            name=op.f("fk_technology_domain_id_domain"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["merged_into"],
            ["technology.id"],
            name=op.f("fk_technology_merged_into_technology"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technology")),
        sa.UniqueConstraint("slug", name=op.f("uq_technology_slug")),
    )
    op.create_index("ix_technology_domain_id", "technology", ["domain_id"], unique=False)
    op.create_index(
        "ix_technology_embedding",
        "technology",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_technology_search_tsv",
        "technology",
        ["search_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "development_organization",
        sa.Column("development_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "role IN ('developer', 'partner', 'funder', 'evaluator', 'regulator')",
            name=op.f("ck_development_organization_role_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["development_id"],
            ["development.id"],
            name=op.f("fk_development_organization_development_id_development"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_development_organization_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "development_id", "organization_id", "role", name=op.f("pk_development_organization")
        ),
    )
    op.create_table(
        "development_technology",
        sa.Column("development_id", sa.UUID(), nullable=False),
        sa.Column("technology_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["development_id"],
            ["development.id"],
            name=op.f("fk_development_technology_development_id_development"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technology.id"],
            name=op.f("fk_development_technology_technology_id_technology"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "development_id", "technology_id", name=op.f("pk_development_technology")
        ),
    )
    op.create_table(
        "technology_alias",
        sa.Column("technology_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technology.id"],
            name=op.f("fk_technology_alias_technology_id_technology"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("technology_id", "alias", name=op.f("pk_technology_alias")),
    )
    op.create_table(
        "claim",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("development_id", sa.UUID(), nullable=True),
        sa.Column(
            "text", sa.Text(), nullable=False, comment="The claim, normalised into one sentence."
        ),
        sa.Column(
            "quote",
            sa.Text(),
            nullable=False,
            comment="Verbatim from the source. Verified as a substring.",
        ),
        sa.Column("quote_verified", sa.Boolean(), nullable=False),
        sa.Column("claim_type", sa.Text(), nullable=False),
        sa.Column("epistemic_label", sa.Text(), nullable=False),
        sa.Column("date_referenced", sa.Date(), nullable=True),
        sa.Column("date_basis", sa.Text(), nullable=True),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="[{name, value, unit}]. Every value must appear in the quote.",
        ),
        sa.Column(
            "subjects",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Mentions as the model found them: [{kind, surface, resolved_id}]. Resolution to an entity is deterministic, never a model decision.",
        ),
        sa.Column("status", sa.Text(), server_default="proposed", nullable=False),
        sa.Column(
            "conflicts_with", postgresql.ARRAY(sa.UUID()), server_default="{}", nullable=False
        ),
        sa.Column("analysis_run_id", sa.UUID(), nullable=False),
        sa.Column("review_action_id", sa.UUID(), nullable=True),
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', text)", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "claim_type IN ('measured_result', 'demonstration', 'deployment', 'regulatory_event', 'funding_or_investment', 'self_reported_claim', 'expectation', 'expert_forecast', 'opinion')",
            name=op.f("ck_claim_claim_type_valid"),
        ),
        sa.CheckConstraint(
            "claim_type NOT IN ('expectation', 'expert_forecast') OR epistemic_label <> 'observed_fact'",
            name=op.f("ck_claim_forecast_is_not_observed_fact"),
        ),
        sa.CheckConstraint(
            "date_referenced IS NULL OR (date_basis IS NOT NULL AND date_basis IN ('document_metadata', 'quoted_text'))",
            name=op.f("ck_claim_date_has_basis"),
        ),
        sa.CheckConstraint(
            "epistemic_label IN ('observed_fact', 'source_expectation', 'expert_forecast')",
            name=op.f("ck_claim_epistemic_label_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'confirmed', 'rejected', 'retracted')",
            name=op.f("ck_claim_status_valid"),
        ),
        sa.CheckConstraint("length(quote) > 0", name=op.f("ck_claim_quote_not_empty")),
        sa.CheckConstraint("quote_verified", name=op.f("ck_claim_quote_must_be_verified")),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_run.id"],
            name=op.f("fk_claim_analysis_run_id_analysis_run"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["development_id"],
            ["development.id"],
            name=op.f("fk_claim_development_id_development"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["source_document.id"],
            name=op.f("fk_claim_document_id_source_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["review_action_id"],
            ["review_action.id"],
            name=op.f("fk_claim_review_action_id_review_action"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim")),
    )
    op.create_index("ix_claim_development_id", "claim", ["development_id"], unique=False)
    op.create_index("ix_claim_document_id", "claim", ["document_id"], unique=False)
    op.create_index(
        "ix_claim_search_tsv", "claim", ["search_tsv"], unique=False, postgresql_using="gin"
    )
    op.create_index("ix_claim_status_claim_type", "claim", ["status", "claim_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_claim_status_claim_type", table_name="claim")
    op.drop_index("ix_claim_search_tsv", table_name="claim", postgresql_using="gin")
    op.drop_index("ix_claim_document_id", table_name="claim")
    op.drop_index("ix_claim_development_id", table_name="claim")
    op.drop_table("claim")
    op.drop_table("technology_alias")
    op.drop_table("development_technology")
    op.drop_table("development_organization")
    op.drop_index("ix_technology_search_tsv", table_name="technology", postgresql_using="gin")
    op.drop_index(
        "ix_technology_embedding",
        table_name="technology",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index("ix_technology_domain_id", table_name="technology")
    op.drop_table("technology")
    op.drop_table("review_action")
    op.drop_index("ix_development_search_tsv", table_name="development", postgresql_using="gin")
    op.drop_index("ix_development_occurred_on", table_name="development")
    op.drop_index(
        "ix_development_embedding",
        table_name="development",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("development")
    op.drop_index("ix_review_task_target_type_target_id", table_name="review_task")
    op.drop_index("ix_review_task_status_priority", table_name="review_task")
    op.drop_table("review_task")
    op.drop_index("ix_organization_name", table_name="organization")
    op.drop_table("organization")
    op.drop_table("domain")
    op.drop_index("ix_analysis_run_stage_created_at", table_name="analysis_run")
    op.drop_table("analysis_run")
    # ### end Alembic commands ###
